# pylint: disable=all
from rdkit.Chem import Mol

def MolLogP(mol: Mol, includeHs: bool = True, force: bool = False) -> float: ...
def MolMR(mol: Mol, includeHs: bool = True, force: bool = False) -> float: ...
