# pylint: disable=all
from rdkit.Chem import Mol

def MolWt(mol: Mol, onlyHeavy: bool = False) -> float: ...
def ExactMolWt(mol: Mol, onlyHeavy: bool = False) -> float: ...
def HeavyAtomMolWt(mol: Mol) -> float: ...
