# pylint: disable=all
from __future__ import annotations

from typing import Optional, Sequence

__all__ = ["Mol", "Atom", "Conformer", "AtomPDBResidueInfo"]

class Mol:
    def GetNumAtoms(self) -> int: ...
    def GetNumConformers(self) -> int: ...
    def GetConformer(self, id: int = -1) -> Conformer: ...
    def GetAtoms(self) -> Sequence[Atom]: ...
    def HasSubstructMatch(
        self,
        query: Mol,
        recursionPossible: bool = True,
        useChirality: bool = False,
        useQueryQueryMatches: bool = False,
    ) -> bool: ...
    def GetSubstructMatch(
        self, query: Mol, useChirality: bool = False, useQueryQueryMatches: bool = False
    ) -> tuple[int, ...]: ...

class Atom:
    def GetPDBResidueInfo(self) -> Optional[AtomPDBResidueInfo]: ...

class Conformer:
    def Is3D(self) -> bool: ...

class AtomPDBResidueInfo:
    def GetResidueNumber(self) -> int: ...
    def GetResidueName(self) -> str: ...
