# pylint: disable=all
from __future__ import annotations

from rdkit.Chem import Mol

def MolFromSmiles(SMILES: str, sanitize: bool = True, removeHs: bool = True) -> Mol: ...
def MolFromMolBlock(
    molBlock: str, sanitize: bool = True, removeHs: bool = True, strictParsing: bool = True
) -> Mol: ...
def MolFromPDBFile(
    molFileName: str, sanitize: bool = True, removeHs: bool = True, flavor: int = 0, proximityBonding: bool = True
) -> Mol: ...
def MolFromSequence(text: str, sanitize: bool = True, flavor: int = 0) -> Mol: ...
def MolFromSmarts(SMARTS: str, mergeHs: bool = False) -> Mol: ...
